export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const VERIFY_SUCCESS = "VERIFY_SUCCESS";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";

export const FETCH_SESSIONS_SUCCESS = "FETCH_SESSIONS_SUCCESS";
