//Auth

export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const VERIFY_SUCCESS = "VERIFY_SUCCESS";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";

export const CHANGE_LANG_SUCCESS = "CHANGE_LANG_SUCCESS";

//Users
export const FETCH_USERS_SUCCESS = "FETCH_USERS_SUCCESS";
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
export const EDIT_USER_SUCCESS = "EDIT_USER_SUCCESS";
export const FETCH_USER_PROFILE_SUCCESS = "FETCH_USER_PROFILE_SUCCESS";
export const FILTER_USERS = "FILTER_USERS";

//Sessions
export const FETCH_SESSIONS_SUCCESS = "FETCH_SESSIONS_SUCCESS";
